- name: To print form play 01
  hosts: local
  connection: local
  tasks:
  - name: To print from play 01 and task 01
    ansible.builtin.debug:
      msg: "This is play 01 and task 01"
  - name: To print from play 01 and task 02
    ansible.builtin.debug:
      msg: "This is play 01 and task 02"    

- name: To print form play 02
  hosts: local
  connection: local
  tasks:
  - name: To print from play 02 and task 01
    ansible.builtin.debug:
      msg: "This is play 02 and task 01"
  - name: To print from play 02 and task 01
    ansible.builtin.debug:
      msg: "This is play 02 and task 02"    