- name: To print vars from inventory
  hosts: local
  connection: local
  tasks:
  - name: To print vars from inventory
    ansible.builtin.debug:
      msg: "course: {{ COURSE }}, duration: {{ DURATION }}"