- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-042fe005f1e4d6ce9
    Zone_id: Z09840842N3EBL36M5Y7S
    domain_name: daws38sat.fun
    instances:
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: {{ sg_id: }}
      image_id: {{ ami_id: }}
      subnet_id: subnet-06dc23984fd523dd0
      state: present
    tags:
      Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2-output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mongodb.daws86s.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"    
